Lombok plugin 8.0.1 -> 8.4
This is required to avoid build errors on OpenJDK 21+

Example error:
```
* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
```

The underlying fix is [apparently](https://stackoverflow.com/a/77171271) to bump Lombok 1.18.30